"use client";

import { useState } from "react";
import { Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";

/**
 * "AI insights" card for the Reports page. On demand it asks the server to
 * analyse the current period's aggregated figures and shows a plain-English
 * summary. Falls back to a rule-based summary when no OpenAI key is set.
 */
export function AiInsights({ days }: { days: number }) {
  const [loading, setLoading] = useState(false);
  const [insights, setInsights] = useState("");
  const [source, setSource] = useState<string | null>(null);
  const [error, setError] = useState("");

  async function analyze() {
    setLoading(true);
    setError("");
    try {
      const res = await fetch("/api/insights", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ days }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.error ?? "Request failed");
      setInsights(data.insights);
      setSource(data.source);
    } catch {
      setError("Couldn't generate insights just now. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="rounded-2xl border border-line bg-surface p-5">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <h2 className="flex items-center gap-2 font-display text-base font-semibold text-brown-900">
          <Sparkles className="h-4 w-4 text-yolk-500" />
          AI insights
        </h2>
        <Button size="sm" variant="primary" loading={loading} onClick={analyze}>
          {insights ? "Re-analyze" : "Analyze with AI"}
        </Button>
      </div>

      {error && <p className="mt-3 text-sm text-danger">{error}</p>}

      {insights ? (
        <>
          <div className="mt-4 whitespace-pre-wrap text-sm leading-relaxed text-brown-800">
            {insights}
          </div>
          <p className="mt-3 text-xs text-muted">
            {source && source !== "rules"
              ? `Generated by AI (${source}) from this period's aggregated figures — no customer data leaves the server.`
              : "Rule-based summary. Add a GEMINI_API_KEY (free tier) or OPENAI_API_KEY for a richer AI analysis."}
          </p>
        </>
      ) : (
        !loading &&
        !error && (
          <p className="mt-3 text-sm text-muted">
            Generate a plain-English summary of this period — top grades, payment
            mix, trends, and what to act on next.
          </p>
        )
      )}
    </div>
  );
}
